/**
 * ISOLATED DEVELOPMENT / DEMO DATASET
 *
 * This file contains strictly isolated mock fixtures for development, preview,
 * offline demonstrations, and UI unit testing when the AIShield backend API
 * is unavailable or running in standalone demo mode.
 *
 * It is NEVER used in live production requests when the API is reachable.
 */

import type {
  DebtHistoryEntry,
  DisplayFinding,
  PullRequestSummary,
  RepositorySummary,
  ScanDetails,
} from '../types/index.js';

export const MOCK_REPOSITORIES: RepositorySummary[] = [
  {
    id: 'repo-odoo-001',
    name: 'Odoo_Hackathon_2026',
    fullName: 'VENUGOPALREDDY787/Odoo_Hackathon_2026',
    defaultBranch: 'main',
    primaryLanguage: 'Python',
    currentScore: 79.0,
    previousScore: 45.0,
    scoreDelta: 34.0,
    currentGrade: 'D',
    totalDebtPoints: 95.0,
    activeFindingsCount: 4,
    criticalFindingsCount: 2,
    highFindingsCount: 1,
    mediumFindingsCount: 1,
    lowFindingsCount: 0,
    trend: 'worsening',
    lastScannedAt: new Date().toISOString(),
    lastScanStatus: 'succeeded',
    scanEnabled: true,
  },
  {
    id: 'repo-wanderlust-002',
    name: 'Wanderlust',
    fullName: 'VENUGOPALREDDY787/Wanderlust',
    defaultBranch: 'main',
    primaryLanguage: 'JavaScript',
    currentScore: 78.0,
    previousScore: 30.0,
    scoreDelta: 48.0,
    currentGrade: 'D',
    totalDebtPoints: 75.0,
    activeFindingsCount: 3,
    criticalFindingsCount: 2,
    highFindingsCount: 0,
    mediumFindingsCount: 1,
    lowFindingsCount: 0,
    trend: 'worsening',
    lastScannedAt: new Date(Date.now() - 3600000).toISOString(),
    lastScanStatus: 'succeeded',
    scanEnabled: true,
  },
  {
    id: 'repo-aishield-003',
    name: 'AIShield',
    fullName: 'VENUGOPALREDDY787/AIShield',
    defaultBranch: 'main',
    primaryLanguage: 'TypeScript',
    currentScore: 0.0,
    previousScore: 86.0,
    scoreDelta: -86.0,
    currentGrade: 'A',
    totalDebtPoints: 0.0,
    activeFindingsCount: 0,
    criticalFindingsCount: 0,
    highFindingsCount: 0,
    mediumFindingsCount: 0,
    lowFindingsCount: 0,
    trend: 'improving',
    lastScannedAt: new Date().toISOString(),
    lastScanStatus: 'succeeded',
    scanEnabled: true,
  },
  {
    id: 'repo-api-002',
    name: 'auth-gateway',
    fullName: 'aishield/auth-gateway',
    defaultBranch: 'main',
    primaryLanguage: 'Go',
    currentScore: 92.0,
    previousScore: 92.0,
    scoreDelta: 0.0,
    currentGrade: 'A',
    totalDebtPoints: 8.0,
    activeFindingsCount: 2,
    criticalFindingsCount: 0,
    highFindingsCount: 0,
    mediumFindingsCount: 1,
    lowFindingsCount: 1,
    trend: 'stable',
    lastScannedAt: new Date(Date.now() - 3600000 * 12).toISOString(),
    lastScanStatus: 'succeeded',
    scanEnabled: true,
  },
  {
    id: 'repo-billing-003',
    name: 'billing-service',
    fullName: 'aishield/billing-service',
    defaultBranch: 'master',
    primaryLanguage: 'Python',
    currentScore: 48.0,
    previousScore: 55.0,
    scoreDelta: -7.0,
    currentGrade: 'D',
    totalDebtPoints: 52.0,
    activeFindingsCount: 11,
    criticalFindingsCount: 2,
    highFindingsCount: 4,
    mediumFindingsCount: 3,
    lowFindingsCount: 2,
    trend: 'worsening',
    lastScannedAt: new Date(Date.now() - 3600000 * 5).toISOString(),
    lastScanStatus: 'succeeded',
    scanEnabled: true,
  },
];

export const MOCK_FINDINGS: DisplayFinding[] = [
  {
    id: 'finding-odoo-001',
    repositoryId: 'repo-odoo-001',
    fingerprint: 'sha256:odoo-sqli-cursor-01',
    title: 'Direct SQL String Formatting in Cursor Execute (SQLi)',
    description:
      'User-controlled parameters are formatted directly into raw PostgreSQL queries bypassing Odoo ORM sanitization.',
    severity: 'CRITICAL',
    category: 'SAST',
    source: 'semgrep',
    confidence: 0.99,
    filePath: 'models/account_move.py',
    line: 34,
    snippet: "self.env.cr.execute(\"SELECT id, state, amount_total FROM account_move WHERE ref = '%s'\" % user_ref)",
    snippetRedacted: false,
    cwe: 'CWE-89',
    owasp: 'A03:2021-Injection',
    tags: ['python', 'odoo', 'sast', 'sqli'],
    status: 'open',
    isNewInPr: true,
    timesDetected: 2,
    firstDetectedAt: new Date().toISOString(),
    lastDetectedAt: new Date().toISOString(),
    aiAnalysis: {
      summary: 'Raw string formatting inside cursor execution allows arbitrary SQL injection in PostgreSQL database.',
      exploitability: 'high',
      reachability: 'reachable',
      businessImpact: 'Unauthorized read/write access to financial invoices and company accounts in Odoo.',
      falsePositiveLikelihood: 0.01,
      confidence: 0.99,
    },
    remediation: {
      summary: "Use parameterized query placeholders: self.env.cr.execute('SELECT id, state FROM account_move WHERE ref = %s', (user_ref,))",
      steps: [
        'Replace string formatting % with parameterized tuple',
        'Use Odoo standard search/read ORM methods where possible',
      ],
      effort: 'small',
      autoFixAvailable: true,
      suggestedPatch: "@@ -34,1 +34,1 @@\n- self.env.cr.execute(\"SELECT id, state, amount_total FROM account_move WHERE ref = '%s'\" % user_ref)\n+ self.env.cr.execute(\"SELECT id, state, amount_total FROM account_move WHERE ref = %s\", (user_ref,))",
    },
  },
  {
    id: 'finding-odoo-002',
    repositoryId: 'repo-odoo-001',
    fingerprint: 'sha256:odoo-secret-admin-02',
    title: 'Exposed Odoo Database Master Password in Configuration',
    description: 'Hardcoded admin master password discovered in odoo.conf configuration file.',
    severity: 'CRITICAL',
    category: 'SECRET',
    source: 'gitleaks',
    confidence: 1.0,
    filePath: 'config/odoo.conf',
    line: 12,
    snippet: 'admin_passwd = "super_admin_master_key_odoo2026_prod!"',
    snippetRedacted: true,
    cwe: 'CWE-798',
    owasp: 'A07:2021-Identification and Authentication Failures',
    tags: ['secrets', 'credentials', 'gitleaks'],
    status: 'open',
    isNewInPr: true,
    timesDetected: 1,
    firstDetectedAt: new Date().toISOString(),
    lastDetectedAt: new Date().toISOString(),
    aiAnalysis: {
      summary: 'Master database administrative password exposed in plaintext. Anyone with repo access can drop or duplicate database schemas.',
      exploitability: 'high',
      reachability: 'reachable',
      businessImpact: 'Total database compromise and administrative takeover of the Odoo cluster.',
      falsePositiveLikelihood: 0.0,
      confidence: 1.0,
    },
    remediation: {
      summary: 'Remove plaintext master password from odoo.conf and inject via environment variables (ODOO_MASTER_PASSWD).',
      steps: [
        'Rotate master admin password immediately in PostgreSQL',
        'Store encrypted password hash or inject dynamically via docker-compose environment variable',
      ],
      effort: 'small',
      autoFixAvailable: true,
    },
  },
  {
    id: 'finding-odoo-003',
    repositoryId: 'repo-odoo-001',
    fingerprint: 'sha256:odoo-idor-portal-03',
    title: 'Unrestricted .sudo() Execution Without ACL Ownership Guard (IDOR)',
    description: 'Customer records are updated in elevated sudo() context without verifying that the requesting portal user owns the target partner record.',
    severity: 'HIGH',
    category: 'AI_CONTEXTUAL',
    source: 'ai_analyzer',
    confidence: 0.93,
    filePath: 'controllers/portal.py',
    line: 58,
    snippet: "partner = request.env['res.partner'].sudo().browse(partner_id)\npartner.write(values)",
    snippetRedacted: false,
    cwe: 'CWE-285',
    owasp: 'A01:2021-Broken Access Control',
    tags: ['ai-contextual', 'idor', 'access-control'],
    status: 'open',
    isNewInPr: true,
    timesDetected: 1,
    firstDetectedAt: new Date().toISOString(),
    lastDetectedAt: new Date().toISOString(),
    aiAnalysis: {
      summary: 'AI Contextual model detected IDOR vulnerability: unauthenticated or regular portal users can modify other users partner records.',
      exploitability: 'high',
      reachability: 'reachable',
      businessImpact: 'Unauthorized tampering with sensitive customer PII and contact data.',
      falsePositiveLikelihood: 0.04,
      confidence: 0.94,
    },
    remediation: {
      summary: 'Enforce access rule check: verify request.env.user.partner_id.id == partner_id before executing .sudo().write().',
      steps: [
        'Add ownership check in controller',
        'Ensure sudo() is only used for background computed fields, not direct user input',
      ],
      effort: 'medium',
      autoFixAvailable: true,
    },
  },
  {
    id: 'finding-wanderlust-001',
    repositoryId: 'repo-wanderlust-002',
    fingerprint: 'sha256:wl-jwt-secret-01',
    title: 'Hardcoded Static JWT Secret Key',
    description: 'Static JWT signing secret key was committed directly in application controller code.',
    severity: 'CRITICAL',
    category: 'SECRET',
    source: 'gitleaks',
    confidence: 1.0,
    filePath: 'controllers/listings.js',
    line: 5,
    snippet: 'const JWT_SECRET = "production_super_secret_jwt_key_99887766";',
    snippetRedacted: true,
    cwe: 'CWE-798',
    owasp: 'A07:2021-Identification and Authentication Failures',
    tags: ['secrets', 'jwt', 'gitleaks'],
    status: 'open',
    isNewInPr: true,
    timesDetected: 1,
    firstDetectedAt: new Date().toISOString(),
    lastDetectedAt: new Date().toISOString(),
    aiAnalysis: {
      summary: 'Hardcoded JWT secret allows any attacker to forge valid authentication tokens and impersonate administrators.',
      exploitability: 'high',
      reachability: 'reachable',
      businessImpact: 'Total authentication bypass and account takeover.',
      falsePositiveLikelihood: 0.0,
      confidence: 1.0,
    },
    remediation: {
      summary: 'Remove static secret and read from process.env.JWT_SECRET.',
      steps: ['Generate high-entropy random key (crypto.randomBytes(32).toString("hex"))', 'Store in .env file'],
      effort: 'trivial',
      autoFixAvailable: true,
    },
  },
  {
    id: 'finding-wanderlust-002',
    repositoryId: 'repo-wanderlust-002',
    fingerprint: 'sha256:wl-eval-rce-02',
    title: 'Dangerous eval() Code Execution from Query Parameter',
    description: 'User input from query parameter is passed directly into eval(), allowing arbitrary server-side code execution.',
    severity: 'CRITICAL',
    category: 'SAST',
    source: 'semgrep',
    confidence: 0.98,
    filePath: 'controllers/listings.js',
    line: 10,
    snippet: 'eval(req.query.customFilter);',
    snippetRedacted: false,
    cwe: 'CWE-95',
    owasp: 'A03:2021-Injection',
    tags: ['rce', 'eval', 'sast'],
    status: 'open',
    isNewInPr: true,
    timesDetected: 1,
    firstDetectedAt: new Date().toISOString(),
    lastDetectedAt: new Date().toISOString(),
    aiAnalysis: {
      summary: 'Dynamic JavaScript execution of untrusted input enables Remote Code Execution (RCE) on the backend host.',
      exploitability: 'high',
      reachability: 'reachable',
      businessImpact: 'Full host operating system compromise.',
      falsePositiveLikelihood: 0.01,
      confidence: 0.99,
    },
    remediation: {
      summary: 'Remove eval() completely. Parse structured JSON parameters instead.',
      steps: ['Delete eval() statement', 'Use JSON.parse() or a schema validator'],
      effort: 'small',
      autoFixAvailable: true,
    },
  },
  {
    id: 'finding-001',
    repositoryId: 'repo-odoo-001',
    fingerprint: 'sha256:4f8a92b3c1d4e5f6',
    title: 'SQL / NoSQL Injection via Unsanitized Request Parameter',
    description:
      'User input from `req.query.filter` is passed directly into a database query constructor without sanitization, allowing arbitrary query execution.',
    severity: 'CRITICAL',
    category: 'SAST',
    source: 'semgrep',
    confidence: 1.0,
    filePath: 'src/services/query-builder.ts',
    line: 84,
    endLine: 89,
    column: 14,
    snippet: `82 |   const { filter, limit } = req.query;\n83 |   // Direct parameter injection without schema validation\n84 |   const query = { $where: \`this.status == '\${filter}'\` };\n85 |   return await db.collection('audit_logs').find(query).limit(limit);`,
    snippetRedacted: false,
    cwe: 'CWE-89',
    owasp: 'A03:2021-Injection',
    tags: ['owasp-top10', 'sast', 'injection'],
    status: 'open',
    isNewInPr: true,
    timesDetected: 3,
    firstDetectedAt: '2026-09-20T10:00:00.000Z',
    lastDetectedAt: new Date(Date.now() - 3600000 * 2).toISOString(),
    aiAnalysis: {
      summary:
        'The query parameter is evaluated in MongoDB JavaScript sandbox context ($where clause), creating remote code execution exposure.',
      exploitability: 'high',
      reachability: 'reachable',
      businessImpact: 'High risk of complete database exfiltration or server-side script execution.',
      falsePositiveLikelihood: 0.05,
      confidence: 0.95,
    },
    remediation: {
      summary: 'Replace JavaScript $where evaluation with declarative Mongoose/MongoDB query operator.',
      steps: [
        'Remove string interpolation in query builder',
        'Use strict equality operator: { status: String(filter) }',
        'Add Zod/Joi schema validation on incoming query parameters',
      ],
      effort: 'small',
      autoFixAvailable: true,
      suggestedPatch: `@@ -84,2 +84,2 @@\n-  const query = { $where: \`this.status == '\${filter}'\` };\n+  const query = { status: typeof filter === 'string' ? filter : undefined };`,
    },
  },
  {
    id: 'finding-002',
    repositoryId: 'repo-core-001',
    fingerprint: 'sha256:7b2e11a0c9d8e7f4',
    title: 'High-Entropy Secret: Exposed GitHub Personal Access Token',
    description:
      'A personal access token matching the GitHub token pattern (`ghp_...`) was committed in plaintext configuration fixtures.',
    severity: 'HIGH',
    category: 'secrets',
    source: 'gitleaks',
    confidence: 1.0,
    filePath: 'tests/fixtures/ci-config.json',
    line: 18,
    endLine: 18,
    column: 22,
    snippet: `17 |   "environment": "staging",\n18 |   "github_token": "ghp_************************************",\n19 |   "timeout_ms": 30000`,
    snippetRedacted: true,
    cwe: 'CWE-798',
    owasp: 'A07:2021-Identification and Authentication Failures',
    tags: ['secrets', 'credentials', 'gitleaks'],
    status: 'open',
    isNewInPr: true,
    timesDetected: 1,
    firstDetectedAt: new Date(Date.now() - 3600000 * 2).toISOString(),
    lastDetectedAt: new Date(Date.now() - 3600000 * 2).toISOString(),
    aiAnalysis: {
      summary:
        'Test fixture contains what appears to be an active API token. Even in test folders, credentials should not be checked into VCS.',
      exploitability: 'high',
      reachability: 'reachable',
      businessImpact: 'Unauthorized access to GitHub organization repos and actions workflows.',
      falsePositiveLikelihood: 0.02,
      confidence: 0.98,
    },
    remediation: {
      summary: 'Revoke the token immediately in GitHub Settings and inject via GitHub Secrets.',
      steps: [
        'Rotate and revoke token on GitHub immediately',
        'Replace with dummy placeholder in test fixtures',
        'Add pre-commit hook with gitleaks prevent future leaks',
      ],
      effort: 'trivial',
      autoFixAvailable: false,
    },
  },
  {
    id: 'finding-003',
    repositoryId: 'repo-core-001',
    fingerprint: 'sha256:a1b2c3d4e5f60718',
    title: 'Vulnerable Dependency: express < 4.21.2 (CVE-2024-43796 / GHSA-qw6h-v8gh-w36c)',
    description:
      'Path traversal in Express redirect URL handling allows open redirect or SSRF under specific routing configurations.',
    severity: 'MEDIUM',
    category: 'dependency',
    source: 'dependency',
    confidence: 1.0,
    filePath: 'package.json',
    line: 34,
    snippet: `33 |     "cors": "^2.8.5",\n34 |     "express": "4.19.2",\n35 |     "helmet": "^7.1.0"`,
    snippetRedacted: false,
    cwe: 'CWE-601',
    owasp: 'A06:2021-Vulnerable and Outdated Components',
    tags: ['dependency', 'cve', 'osv'],
    status: 'open',
    isNewInPr: false,
    timesDetected: 12,
    firstDetectedAt: '2026-08-15T09:00:00.000Z',
    lastDetectedAt: new Date(Date.now() - 3600000 * 2).toISOString(),
    aiAnalysis: {
      summary: 'Well-known advisory in Express routing. Direct upgrade available without breaking changes.',
      exploitability: 'medium',
      reachability: 'reachable',
      businessImpact: 'Open redirect can facilitate credential phishing of dashboard users.',
      falsePositiveLikelihood: 0.01,
      confidence: 0.99,
    },
    remediation: {
      summary: 'Upgrade express to ^4.21.2 or latest 5.x branch.',
      steps: ['Run npm install express@^4.21.2', 'Run npm test to verify route handlers'],
      effort: 'trivial',
      autoFixAvailable: true,
      suggestedPatch: `@@ -34,1 +34,1 @@\n-    "express": "4.19.2",\n+    "express": "^4.21.2",`,
    },
  },
  {
    id: 'finding-004',
    repositoryId: 'repo-core-001',
    fingerprint: 'sha256:c9e8d7c6b5a4f3e2',
    title: 'Missing Tenant Boundary Check in Batch Organization Export',
    description:
      'AI Analysis detected that the export handler verifies authenticated user membership for the first record but neglects to scope the bulk find query to the request tenant ID.',
    severity: 'HIGH',
    category: 'authorization',
    source: 'ai-analyzer',
    confidence: 0.88,
    filePath: 'src/controllers/export.controller.ts',
    line: 112,
    endLine: 125,
    snippet: `112 |   const { orgId } = req.auth;\n113 |   // AI Note: Query finds all records matching status without filtering by orgId\n114 |   const data = await ReportModel.find({ status: 'completed' });\n115 |   return res.json({ exports: data });`,
    snippetRedacted: false,
    cwe: 'CWE-285',
    owasp: 'A01:2021-Broken Access Control',
    tags: ['ai-contextual', 'business-logic', 'authorization', 'multi-tenant'],
    status: 'open',
    isNewInPr: true,
    timesDetected: 1,
    firstDetectedAt: new Date(Date.now() - 3600000 * 2).toISOString(),
    lastDetectedAt: new Date(Date.now() - 3600000 * 2).toISOString(),
    aiAnalysis: {
      summary:
        'Contextual logic gap: Multi-tenant boundary is missing in the bulk retrieval query, causing cross-tenant data exposure.',
      exploitability: 'high',
      reachability: 'reachable',
      businessImpact: 'Severe: Tenants can read sensitive audit and compliance reports of other organizations.',
      falsePositiveLikelihood: 0.08,
      confidence: 0.88,
    },
    remediation: {
      summary: 'Enforce tenant ID filter in Mongoose find query.',
      steps: [
        'Add organization: orgId to MongoDB query criteria',
        'Add authorization regression test in test/routes/export.test.ts',
      ],
      effort: 'small',
      autoFixAvailable: true,
      suggestedPatch: `@@ -114,1 +114,1 @@\n-  const data = await ReportModel.find({ status: 'completed' });\n+  const data = await ReportModel.find({ organization: orgId, status: 'completed' });`,
    },
  },
  {
    id: 'finding-005',
    repositoryId: 'repo-core-001',
    fingerprint: 'sha256:1122334455667788',
    title: 'Insecure Direct Object Reference (IDOR) in Scan Cancellation',
    description:
      'Scan cancel route permits any authenticated user to cancel scans without verifying repository ownership.',
    severity: 'MEDIUM',
    category: 'authorization',
    source: 'ai-analyzer',
    confidence: 0.84,
    filePath: 'src/routes/scan.routes.ts',
    line: 265,
    snippet: `264 | scanRouter.delete('/:scanId', async (req, res, next) => {\n265 |   const scan = await ScanModel.findById(scanId);\n266 |   // Missing permission check before mutating status`,
    snippetRedacted: false,
    cwe: 'CWE-639',
    owasp: 'A01:2021-Broken Access Control',
    tags: ['ai-contextual', 'idor', 'authorization'],
    status: 'open',
    isNewInPr: false,
    timesDetected: 4,
    firstDetectedAt: '2026-09-10T14:20:00.000Z',
    lastDetectedAt: new Date(Date.now() - 3600000 * 2).toISOString(),
    aiAnalysis: {
      summary: 'Authorization control omitted on mutating endpoint.',
      exploitability: 'medium',
      reachability: 'reachable',
      businessImpact: 'Denial of service for running security scans by unprivileged users.',
      falsePositiveLikelihood: 0.12,
      confidence: 0.84,
    },
    remediation: {
      summary: 'Verify request user owns the repository before executing cancellation.',
      steps: ['Add repository permission check helper', 'Return 403 if user lacks admin role'],
      effort: 'small',
      autoFixAvailable: false,
    },
  },
  {
    id: 'finding-006',
    repositoryId: 'repo-core-001',
    fingerprint: 'sha256:9988776655443322',
    title: 'Missing Rate Limiter on Webhook Dispatch Handler',
    description: 'Endpoint accepts unbounded webhook verification retries without backoff throttling.',
    severity: 'LOW',
    category: 'configuration',
    source: 'semgrep',
    confidence: 0.9,
    filePath: 'src/webhooks/receiver.ts',
    line: 42,
    snippet: `42 | app.post('/webhooks/github', async (req, res) => {\n43 |   verifySignature(req);`,
    snippetRedacted: false,
    cwe: 'CWE-770',
    owasp: 'A05:2021-Security Misconfiguration',
    tags: ['configuration', 'rate-limit'],
    status: 'open',
    isNewInPr: false,
    timesDetected: 8,
    firstDetectedAt: '2026-09-01T12:00:00.000Z',
    lastDetectedAt: new Date(Date.now() - 3600000 * 2).toISOString(),
    remediation: {
      summary: 'Apply rate limiter middleware to public webhook route.',
      steps: ['Mount webhookRateLimit middleware before receiver handler'],
      effort: 'trivial',
      autoFixAvailable: true,
    },
  },
];

export const MOCK_PRS: PullRequestSummary[] = [
  {
    id: 'pr-101',
    repositoryId: 'repo-demo-001',
    repositoryName: 'acme-corp/demo-vulnerable-app',
    number: 101,
    title: 'feat: add AI-assisted user authentication and portal',
    author: 'alex-copilot',
    avatarUrl: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=64&h=64&fit=crop',
    sourceBranch: 'feature/user-portal-vulnerable',
    targetBranch: 'main',
    headSha: '80a59a1e2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e',
    baseSha: '47bc9b6a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e',
    findingsIntroduced: 4,
    findingsResolved: 0,
    scoreDelta: -84.0,
    status: 'open',
    checkStatus: 'FAIL',
    changedFilesCount: 4,
    analyzedAt: new Date(Date.now() - 3600000 * 3).toISOString(),
  },
  {
    id: 'pr-102',
    repositoryId: 'repo-demo-001',
    repositoryName: 'acme-corp/demo-vulnerable-app',
    number: 102,
    title: 'fix: harden application & resolve security debt',
    author: 'sarah-sec',
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=64&h=64&fit=crop',
    sourceBranch: 'pr-4-full-hardening',
    targetBranch: 'main',
    headSha: 'a0ce028e2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e',
    baseSha: '80a59a1e2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e',
    findingsIntroduced: 0,
    findingsResolved: 4,
    scoreDelta: 68.0,
    status: 'merged',
    checkStatus: 'PASS',
    changedFilesCount: 4,
    analyzedAt: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: 'pr-42',
    repositoryId: 'repo-core-001',
    repositoryName: 'aishield/aishield-core',
    number: 42,
    title: 'feat: add AI prompt router and multi-tenant export endpoint',
    author: 'alice-dev',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=64&h=64&fit=crop',
    sourceBranch: 'feat/ai-router-export',
    targetBranch: 'main',
    headSha: '8f7d9a1c2b3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a',
    baseSha: '1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b',
    findingsIntroduced: 3,
    findingsResolved: 1,
    scoreDelta: -6.5,
    status: 'open',
    checkStatus: 'FAIL',
    changedFilesCount: 7,
    analyzedAt: new Date(Date.now() - 3600000 * 2).toISOString(),
  },
  {
    id: 'pr-41',
    repositoryId: 'repo-core-001',
    repositoryName: 'aishield/aishield-core',
    number: 41,
    title: 'fix: patch vulnerable lodash prototype pollution (CVE-2023-26159)',
    author: 'bob-sec',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=64&h=64&fit=crop',
    sourceBranch: 'fix/lodash-upgrade',
    targetBranch: 'main',
    headSha: '2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c',
    baseSha: '0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b',
    findingsIntroduced: 0,
    findingsResolved: 2,
    scoreDelta: 8.0,
    status: 'merged',
    checkStatus: 'PASS',
    changedFilesCount: 2,
    analyzedAt: '2026-09-24T14:30:00.000Z',
  },
  {
    id: 'pr-40',
    repositoryId: 'repo-core-001',
    repositoryName: 'aishield/aishield-core',
    number: 40,
    title: 'refactor: enforce timing-safe API key comparison in auth gateway',
    author: 'carol-arch',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=64&h=64&fit=crop',
    sourceBranch: 'refactor/timing-safe-auth',
    targetBranch: 'main',
    headSha: '3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d',
    baseSha: '9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b',
    findingsIntroduced: 0,
    findingsResolved: 1,
    scoreDelta: 5.0,
    status: 'merged',
    checkStatus: 'PASS',
    changedFilesCount: 3,
    analyzedAt: '2026-09-22T09:15:00.000Z',
  },
];

export const MOCK_SCANS: ScanDetails[] = [
  {
    id: 'scan-20260926-001',
    repositoryId: 'repo-core-001',
    repositoryName: 'aishield/aishield-core',
    commitSha: '8f7d9a1c2b3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a',
    branch: 'feat/ai-router-export',
    baseSha: '1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b',
    trigger: 'pull_request',
    status: 'succeeded',
    enqueuedAt: new Date(Date.now() - 3600000 * 2 - 120000).toISOString(),
    startedAt: new Date(Date.now() - 3600000 * 2 - 110000).toISOString(),
    finishedAt: new Date(Date.now() - 3600000 * 2).toISOString(),
    durationMs: 110000,
    score: 78.5,
    previousScore: 85.0,
    delta: -6.5,
    grade: 'B',
    riskLevel: 'HIGH',
    formulaSummary: 'Base: 100 - (1 Critical × 25.0 + 2 High × 12.0 + 2 Medium × 4.0 + 1 Low × 1.0) / Saturation Scale',
    components: [
      {
        source: 'semgrep',
        status: 'succeeded',
        toolVersion: '1.88.0',
        durationMs: 14500,
        findingCount: 2,
      },
      {
        source: 'gitleaks',
        status: 'succeeded',
        toolVersion: '8.21.2',
        durationMs: 3200,
        findingCount: 1,
      },
      {
        source: 'dependency',
        status: 'succeeded',
        toolVersion: 'osv-scanner-v1.8.4',
        durationMs: 9800,
        findingCount: 1,
      },
      {
        source: 'ai-analyzer',
        status: 'succeeded',
        toolVersion: 'google-genai / gemini-2.5-flash',
        durationMs: 18400,
        findingCount: 2,
      },
    ],
    summary: {
      totalFindings: 6,
      newFindings: 3,
      resolvedFindings: 1,
      bySeverity: {
        CRITICAL: 1,
        HIGH: 2,
        MEDIUM: 2,
        LOW: 1,
        INFO: 0,
      },
      byCategory: {
        injection: 1,
        secrets: 1,
        dependency: 1,
        authorization: 2,
        configuration: 1,
      },
    },
    findingIds: ['finding-001', 'finding-002', 'finding-003', 'finding-004', 'finding-005', 'finding-006'],
  },
];

export const MOCK_DEBT_HISTORY: DebtHistoryEntry[] = [
  {
    id: 'hist-001',
    repositoryId: 'repo-core-001',
    event: 'baseline',
    overallScore: 68.0,
    grade: 'D',
    trend: 'stable',
    severityBreakdown: { CRITICAL: 2, HIGH: 4, MEDIUM: 6, LOW: 5, INFO: 8 },
    categoryBreakdown: { injection: 2, dependency: 4, secrets: 2, authorization: 3 },
    findingCounts: { total: 17, open: 17, new: 17, resolved: 0 },
    recordedAt: '2026-08-01T12:00:00.000Z',
  },
  {
    id: 'hist-002',
    repositoryId: 'repo-core-001',
    event: 'remediation_applied',
    overallScore: 75.0,
    previousScore: 68.0,
    delta: 7.0,
    grade: 'C',
    trend: 'improving',
    severityBreakdown: { CRITICAL: 1, HIGH: 3, MEDIUM: 5, LOW: 4, INFO: 8 },
    categoryBreakdown: { injection: 1, dependency: 3, secrets: 1, authorization: 2 },
    findingCounts: { total: 13, open: 13, new: 0, resolved: 4 },
    recordedAt: '2026-08-18T16:00:00.000Z',
  },
  {
    id: 'hist-003',
    repositoryId: 'repo-core-001',
    event: 'scan_completed',
    overallScore: 82.0,
    previousScore: 75.0,
    delta: 7.0,
    grade: 'B',
    trend: 'improving',
    severityBreakdown: { CRITICAL: 0, HIGH: 2, MEDIUM: 3, LOW: 2, INFO: 6 },
    categoryBreakdown: { dependency: 2, secrets: 1, authorization: 1, configuration: 1 },
    findingCounts: { total: 7, open: 7, new: 1, resolved: 7 },
    recordedAt: '2026-09-10T11:00:00.000Z',
  },
  {
    id: 'hist-004',
    repositoryId: 'repo-core-001',
    event: 'scan_completed',
    overallScore: 85.0,
    previousScore: 82.0,
    delta: 3.0,
    grade: 'B',
    trend: 'improving',
    severityBreakdown: { CRITICAL: 0, HIGH: 1, MEDIUM: 2, LOW: 2, INFO: 6 },
    categoryBreakdown: { dependency: 1, authorization: 1, configuration: 1 },
    findingCounts: { total: 4, open: 4, new: 0, resolved: 3 },
    recordedAt: '2026-09-22T09:15:00.000Z',
  },
  {
    id: 'hist-005',
    repositoryId: 'repo-core-001',
    event: 'scan_completed',
    overallScore: 78.5,
    previousScore: 85.0,
    delta: -6.5,
    grade: 'B',
    trend: 'worsening',
    severityBreakdown: { CRITICAL: 1, HIGH: 2, MEDIUM: 2, LOW: 1, INFO: 0 },
    categoryBreakdown: { injection: 1, secrets: 1, dependency: 1, authorization: 2, configuration: 1 },
    findingCounts: { total: 6, open: 6, new: 3, resolved: 1 },
    recordedAt: new Date(Date.now() - 3600000 * 2).toISOString(),
    scanId: 'scan-20260926-001',
    pullRequestId: 'pr-42',
  },
];
